---

- hosts: "mcs1"
  name: "Configure MaxScale"
  become: true
  become_user: root
  vars_files:
    # yamllint disable-line rule:line-length
    - '../inventory/group_vars/distro/{{ ansible_distribution|lower }}{{ ansible_distribution_major_version }}.yml'

  tasks:

    - name: "Creating Basic MaxScale Config"
      ansible.builtin.copy:
        dest: /etc/maxscale.cnf
        mode: '0660'
        owner: maxscale
        group: maxscale
        content: |
          [maxscale]
          threads=auto
          admin_host=0.0.0.0
          admin_secure_gui=false

    - name: "Clearing MaxScale"
      ansible.builtin.uri:
        url: http://127.0.0.1:8989/v1/{{ item.resource }}/{{ item.name }}
        method: DELETE
        user: admin
        password: mariadb
        status_code: 204,404
      loop:
        - {resource: monitors, name: 'mcs_monitor?force=yes'}
        - {resource: services, name: 'mcs_service?force=yes'}
        - {resource: listeners, name: mcs_listener}
        - {resource: filters, name: mcs_cache}
        - {resource: servers, name: mcs1}

    - name: "Restarting MaxScale"
      ansible.builtin.systemd:
        state: restarted
        name: maxscale

    - name: "Adding Servers To MaxScale"
      ansible.builtin.uri:
        url: http://127.0.0.1:8989/v1/servers
        method: POST
        body_format: json
        # yamllint disable-line rule:line-length
        body: {"data":{"id":"{{ item.name }}", "type":"servers", "attributes":{"parameters":{"address":"{{ item.host }}", "port":"{{ mariadb_port }}", "protocol":"MariaDBBackend"}}}}
        user: admin
        password: mariadb
        status_code: 204
      loop:
        - {"name": "mcs1", "host": "127.0.0.1"}
      no_log: true

    - name: "Adding Query Cache To MaxScale"
      ansible.builtin.uri:
        url: http://127.0.0.1:8989/v1/filters
        method: POST
        body_format: json
        # yamllint disable-line rule:line-length
        body: {"data":{"id":"mcs_cache", "type":"filters", "attributes":{"module":"cache", "parameters":{"max_size":"5G", "storage":"storage_inmemory", "cached_data":"shared"}}}}
        user: admin
        password: mariadb
        status_code: 204
      no_log: false

    - name: "Adding Monitor To MaxScale"
      ansible.builtin.uri:
        url: http://127.0.0.1:8989/v1/monitors
        method: POST
        body_format: json
        # yamllint disable-line rule:line-length
        body: {"data":{"id":"mcs_monitor", "type":"monitors", "attributes":{"module":"mariadbmon", "parameters":{"user":"{{ maxscale_user }}", "password":"{{ maxscale_pass }}", "cooperative_monitoring_locks":"majority_of_running", "enforce_read_only_slaves":true, "auto_failover":true, "auto_rejoin":true}}, "relationships":{"servers":{"data":[{"id":"mcs1", "type":"servers"}]}}}}
        user: admin
        password: mariadb
        status_code: 204
      no_log: true

    - name: "Adding Service To MaxScale"
      ansible.builtin.uri:
        url: http://127.0.0.1:8989/v1/services
        method: POST
        body_format: json
        # yamllint disable-line rule:line-length
        body: {"data":{"id":"mcs_service", "type":"services", "attributes":{"router":"readwritesplit", "parameters":{"user":"{{ maxscale_user }}", "password":"{{ maxscale_pass }}", "master_accept_reads":true, "filters":"mcs_cache"}}, "relationships":{"servers":{"data":[{"id":"mcs1", "type":"servers"}]}}}}
        user: admin
        password: mariadb
        status_code: 204
      no_log: true

    - name: "Adding Listener To MaxScale"
      ansible.builtin.uri:
        url: http://127.0.0.1:8989/v1/listeners
        method: POST
        body_format: json
        # yamllint disable-line rule:line-length
        body: {"data":{"id":"mcs_listener", "type":"listeners", "attributes":{"parameters":{"protocol":"MariaDBClient", "port":"{{ maxscale_port }}"}}, "relationships":{"services":{"data":[{"id":"mcs_service", "type":"services"}]}}}}
        user: admin
        password: mariadb
        status_code: 204
      no_log: false
