---

- hosts: "mcs1"
  name: "Preparing Server"
  become: true
  become_user: root
  vars_files:
    # yamllint disable-line rule:line-length
    - '../inventory/group_vars/distro/{{ ansible_distribution|lower }}{{ ansible_distribution_major_version }}.yml'

  tasks:

    - name: "Scanning For Running Services"
      ansible.builtin.service_facts:

    - name: "Setting SELinux Permissive"
      ansible.posix.selinux:
        policy: targeted
        state: permissive
      when: (ansible_distribution | lower == 'centos') or
            (ansible_distribution | lower == 'rocky')

    - name: "Disabling firewalld"
      ansible.builtin.systemd:
        name: firewalld
        state: stopped
        enabled: false
      when: (ansible_facts.services["firewalld.service"]["state"]) is defined

    - name: "Disabling AppArmor"
      ansible.builtin.systemd:
        name: apparmor
        state: stopped
        enabled: false
      when: ansible_distribution | lower == 'ubuntu'

    - name: "Disabling UFW"
      ansible.builtin.systemd:
        name: ufw
        state: stopped
        enabled: false
      when: (ansible_facts.services["ufw.service"]["state"]) is defined

    - name: "Upgrading All Packages"
      ansible.builtin.package:
        name: '*'
        state: latest
        update_cache: true

    - name: "Rebooting To Apply Updates"
      ansible.builtin.reboot:

    - name: "Installing Some Prerequisites"
      ansible.builtin.package:
        name: '{{ item }}'
        state: present
      with_items:
        - '{{ gcc }}'
        - '{{ git }}'
        - '{{ htop }}'
        - '{{ jemalloc }}'
        - '{{ jq }}'
        - '{{ mlocate }}'
        - '{{ nano }}'
        - '{{ python_dev }}'
        - '{{ python_lxml }}'
        - '{{ python_mysql }}'
        - '{{ wget }}'

    - name: "Setting System Character Set"
      ansible.builtin.command: localedef -i en_US -f UTF-8 en_US.UTF-8
      register: char_output
      changed_when: char_output.rc != 0

    - name: "Optimize ColumnStore Linux Kernel Parameters"
      ansible.builtin.copy:
        dest: /etc/sysctl.d/90-mariadb-columnstore.conf
        mode: '0600'
        content: |
          vm.swappiness = 1
          net.core.rmem_max = 16777216
          net.core.wmem_max = 16777216
          net.ipv4.tcp_rmem = 4096 87380 16777216
          net.ipv4.tcp_wmem = 4096 65536 16777216
          net.ipv4.tcp_no_metrics_save = 1

    - name: "Load ColumnStore Linux Kernel Parameters"
      ansible.posix.sysctl:
        name: net.core.netdev_max_backlog
        value: '{{ netdev_max_backlog }}'
        sysctl_file: /etc/sysctl.d/90-mariadb-columnstore.conf
        reload: true

    - name: "Removing Conflicts"
      ansible.builtin.package:
        name: '{{ mariadb_libs }}'
        state: absent
      # yamllint disable-line rule:line-length
      when: ansible_distribution | lower + ansible_distribution_major_version == "centos7"
